x-common: &common
  restart: unless-stopped
  stop_grace_period: 60s
  volumes:
    - ./data-${INSTANCE}:${DATA_DIR:-/home/steam/Zomboid}
    - ./server-files:/home/steam/pzserver
    - ./backups-${INSTANCE}:${BACKUP_PATH:-/home/steam/Zomboid/backups}

services:
  zomboid-server1:
    <<: *common
    image: ghcr.io/faudil/project-zomboid-server-docker:latest
    container_name: pz-server1
    environment:
      - SERVER_NAME=server1
      - PUBLIC_NAME=Server One
      - DEFAULT_PORT=16261
      - UDP_PORT=16262
      - RCON_PORT=27015
      - MAX_PLAYERS=16
    env_file:
      - .env
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"

  zomboid-server2:
    <<: *common
    image: ghcr.io/faudil/project-zomboid-server-docker:latest
    container_name: pz-server2
    environment:
      - SERVER_NAME=server2
      - PUBLIC_NAME=Server Two
      - DEFAULT_PORT=16263
      - UDP_PORT=16264
      - RCON_PORT=27016
      - MAX_PLAYERS=8
    env_file:
      - .env
    ports:
      - "16263:16263/udp"
      - "16264:16264/udp"
      - "27016:27016/tcp"
