package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func (c *ServerConfig) WriteIni() error {
	dir := filepath.Dir(c.ServerIniPath())
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating server config directory: %w", err)
	}

	var sb strings.Builder

	sb.WriteString("# Generated by project-zomboid-server-docker\n")
	sb.WriteString("# Edit at your own risk - these values are regenerated on container start\n\n")

	sb.WriteString(fmt.Sprintf("PublicName=%s\n", c.PublicName))
	sb.WriteString(fmt.Sprintf("Public=%t\n", c.PublicServer))
	sb.WriteString(fmt.Sprintf("Open=%t\n", c.PublicServer))

	if c.ServerPassword != "" {
		sb.WriteString(fmt.Sprintf("Password=%s\n", c.ServerPassword))
	}

	sb.WriteString(fmt.Sprintf("MaxPlayers=%d\n", c.MaxPlayers))
	sb.WriteString(fmt.Sprintf("DefaultPort=%d\n", c.DefaultPort))
	sb.WriteString(fmt.Sprintf("SteamPort1=%d\n", c.UDPPort))
	sb.WriteString(fmt.Sprintf("RCONPort=%d\n", c.RCONPort))
	sb.WriteString(fmt.Sprintf("RCONPassword=%s\n", c.RCONPassword))
	sb.WriteString(fmt.Sprintf("SteamPort2=%d\n", c.UDPPort+1))
	sb.WriteString(fmt.Sprintf("BindIP=%s\n", c.BindIP))

	pauseEmpty := "true"
	if !c.PauseOnEmpty {
		pauseEmpty = "false"
	}
	sb.WriteString(fmt.Sprintf("PauseEmpty=%s\n", pauseEmpty))

	sb.WriteString(fmt.Sprintf("SaveWorldEveryMinutes=%d\n", c.AutosaveInterval))
	sb.WriteString(fmt.Sprintf("PVP=%t\n", c.PvP))
	sb.WriteString(fmt.Sprintf("SteamVAC=%t\n", c.SteamVAC))

	if c.ModNames != "" {
		sb.WriteString(fmt.Sprintf("Mods=%s\n", c.ModNames))
	}
	if c.ModWorkshopIDs != "" {
		sb.WriteString(fmt.Sprintf("WorkshopItems=%s\n", c.ModWorkshopIDs))
	}

	if c.MapNames != "" {
		sb.WriteString(fmt.Sprintf("Map=%s\n", parseMapNames(c.MapNames)))
	}

	sb.WriteString("VoiceMaxDistance=100.0\n")
	sb.WriteString("ServerWelcomeMessage=Welcome to Project Zomboid!\n")
	sb.WriteString("ServerLogFileName=server-console.txt\n")
	sb.WriteString("LogLocalChat=true\n")
	sb.WriteString("LogGlobalChat=true\n")
	sb.WriteString("SaveTransactionID=false\n")
	sb.WriteString("DisableSafehouse=false\n")
	sb.WriteString("ServerPlayerID=0\n")

	return os.WriteFile(c.ServerIniPath(), []byte(sb.String()), 0644)
}

func parseMapNames(names string) string {
	parts := strings.Split(names, ";")
	var formatted []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			formatted = append(formatted, p)
		}
	}
	return strings.Join(formatted, ";")
}
