package config

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// validIniKeyRE restricts INI_* passthrough keys to plain option names.
// Anything else (sections like [GameOptions], comments, separators) could
// inject extra directives into server.ini.
var validIniKeyRE = regexp.MustCompile(`^[A-Za-z0-9]+$`)

func (c *ServerConfig) WriteIni() error {
	dir := filepath.Dir(c.ServerIniPath())
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating server config directory: %w", err)
	}

	var sb strings.Builder

	sb.WriteString("# Generated by project-zomboid-server-docker\n")
	sb.WriteString("# Edit at your own risk - these values are regenerated on container start\n\n")

	sb.WriteString(fmt.Sprintf("PublicName=%s\n", iniValue(c.PublicName)))
	sb.WriteString(fmt.Sprintf("Public=%t\n", c.PublicServer))
	sb.WriteString(fmt.Sprintf("Open=%t\n", c.PublicServer))

	if c.ServerPassword != "" {
		sb.WriteString(fmt.Sprintf("Password=%s\n", iniValue(c.ServerPassword)))
	}

	sb.WriteString(fmt.Sprintf("MaxPlayers=%d\n", c.MaxPlayers))
	sb.WriteString(fmt.Sprintf("DefaultPort=%d\n", c.DefaultPort))
	sb.WriteString(fmt.Sprintf("SteamPort1=%d\n", c.UDPPort))
	sb.WriteString(fmt.Sprintf("RCONPort=%d\n", c.RCONPort))
	sb.WriteString(fmt.Sprintf("RCONPassword=%s\n", iniValue(c.RCONPassword)))
	sb.WriteString(fmt.Sprintf("SteamPort2=%d\n", c.UDPPort+1))
	sb.WriteString(fmt.Sprintf("BindIP=%s\n", iniValue(c.BindIP)))

	pauseEmpty := "true"
	if !c.PauseOnEmpty {
		pauseEmpty = "false"
	}
	sb.WriteString(fmt.Sprintf("PauseEmpty=%s\n", pauseEmpty))

	sb.WriteString(fmt.Sprintf("SaveWorldEveryMinutes=%d\n", c.AutosaveInterval))
	sb.WriteString(fmt.Sprintf("PVP=%t\n", c.PvP))
	sb.WriteString(fmt.Sprintf("SteamVAC=%t\n", c.SteamVAC))

	if c.ModNames != "" {
		sb.WriteString(fmt.Sprintf("Mods=%s\n", iniValue(c.ModNames)))
	}
	if c.ModWorkshopIDs != "" {
		sb.WriteString(fmt.Sprintf("WorkshopItems=%s\n", iniValue(c.ModWorkshopIDs)))
	}

	if c.MapNames != "" {
		sb.WriteString(fmt.Sprintf("Map=%s\n", iniValue(parseMapNames(c.MapNames))))
	}

	sb.WriteString("VoiceMaxDistance=100.0\n")
	sb.WriteString("ServerWelcomeMessage=Welcome to Project Zomboid!\n")
	sb.WriteString("ServerLogFileName=server-console.txt\n")
	sb.WriteString("LogLocalChat=true\n")
	sb.WriteString("LogGlobalChat=true\n")
	sb.WriteString("SaveTransactionID=false\n")
	sb.WriteString("DisableSafehouse=false\n")
	sb.WriteString("ServerPlayerID=0\n")

	// INI_* env passthrough: INI_SleepAllowed=true becomes SleepAllowed=true.
	// Sorted for deterministic output; keys are validated and values are
	// passed through iniValue to strip anything that could break the format.
	// Keys already written above are skipped so one setting cannot be
	// defined twice in the file.
	fixedKeys := map[string]bool{
		"PublicName": true, "Public": true, "Open": true, "Password": true,
		"MaxPlayers": true, "DefaultPort": true, "SteamPort1": true,
		"RCONPort": true, "RCONPassword": true, "SteamPort2": true,
		"BindIP": true, "PauseEmpty": true, "SaveWorldEveryMinutes": true,
		"PVP": true, "SteamVAC": true, "Mods": true, "WorkshopItems": true,
		"Map": true, "VoiceMaxDistance": true, "ServerWelcomeMessage": true,
		"ServerLogFileName": true, "LogLocalChat": true, "LogGlobalChat": true,
		"SaveTransactionID": true, "DisableSafehouse": true, "ServerPlayerID": true,
	}
	keys := make([]string, 0, len(c.IniOptions))
	for k := range c.IniOptions {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		if fixedKeys[k] {
			fmt.Printf("WARNING: INI_%s is already managed by this image, ignoring\n", k)
			continue
		}
		if !validIniKeyRE.MatchString(k) {
			fmt.Printf("WARNING: INI_%s: invalid key, ignoring (allowed: letters and digits)\n", k)
			continue
		}
		sb.WriteString(fmt.Sprintf("%s=%s\n", k, iniValue(c.IniOptions[k])))
	}

	// The game rewrites this file itself on exit; 0600 keeps the RCON password
	// unreadable to other users in the data bind mount while we own it.
	return os.WriteFile(c.ServerIniPath(), []byte(sb.String()), 0600)
}

// iniValue strips characters that could inject extra ini directives or break
// the format (newlines, carriage returns) from operator-supplied values.
func iniValue(v string) string {
	v = strings.ReplaceAll(v, "\r", "")
	v = strings.ReplaceAll(v, "\n", "")
	return v
}

func parseMapNames(names string) string {
	parts := strings.Split(names, ";")
	var formatted []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			formatted = append(formatted, p)
		}
	}
	return strings.Join(formatted, ";")
}
