package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func (c *ServerConfig) WriteSandboxVars() error {
	dir := filepath.Dir(c.SandboxVarsPath())
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating sandbox vars directory: %w", err)
	}

	vars := map[string]string{
		"Zombies":            "1",
		"Distribution":       "1",
		"DayLength":          "1",
		"StartYear":          "0",
		"StartMonth":         "7",
		"StartDay":           "9",
		"StartTime":          "2",
		"WaterShutModifier":  "14",
		"ElecShutModifier":   "14",
		"WaterShut":          "-1",
		"ElecShut":           "-1",
		"FoodLoot":           "2",
		"WeaponLoot":         "2",
		"OtherLoot":          "2",
		"Temperature":        "3",
		"Rain":               "3",
		"ErosionSpeed":       "3",
		"ErosionDays":        "0",
		"Farming":            "3",
		"CompostTime":        "1",
		"StatsDecrease":      "3",
		"NatureAbundance":    "3",
		"Alarm":              "2",
		"LockedHouses":       "3",
		"Choppers":           "1",
		"GeneratorSpawning":  "2",
		"SurvivorHouses":     "3",
		"VehicleStoryChance": "3",
		"ZoneStoryChance":    "3",
		"AnnotatedMapChance": "2",
		"MonthsSinceApo":     "0",
		"DarknessNight":      "false",
		"Helicopter":         "2",
		"MetaEvent":          "2",
		"SleepingEvent":      "2",
		"ZombieConfig": `{
            SetZombiesCount = 1,
            SetZombiesRespawn = 1,
            SetZombieLore = {
                Speed = 2,
                Strength = 2,
                Toughness = 2,
                Transmission = 1,
                Mortality = 5,
                Reanimate = 3,
                Cognition = 2,
                CrawlUnderVehicle = 5,
                Memory = 2,
                Decomp = 1,
                Sight = 2,
                Hearing = 2,
                Smell = 2,
                ThumpNoChasing = 1,
                ThumpOnConstruction = 1,
                ActiveOnly = 1,
                TriggerHouseAlarm = false,
                ZombiesDragDownOnly = false,
                ZombieFavouriteLoot = false,
            },
        }`,
	}

	for k, v := range c.SandboxVars {
		vars[k] = v
	}

	var sb strings.Builder
	sb.WriteString("-- Generated by project-zomboid-server-docker\n")
	sb.WriteString("SandboxVars = {\n")

	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for i, k := range keys {
		sep := ","
		if i == len(keys)-1 {
			sep = ""
		}
		v := vars[k]
		if strings.HasPrefix(v, `{`) {
			sb.WriteString(fmt.Sprintf("    %s = %s%s\n", k, v, sep))
		} else {
			sb.WriteString(fmt.Sprintf("    %s = %s,%s\n", k, v, sep))
		}
	}

	sb.WriteString("}\n")

	return os.WriteFile(c.SandboxVarsPath(), []byte(sb.String()), 0644)
}
