package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func (c *ServerConfig) WriteSandboxVars() error {
	dir := filepath.Dir(c.SandboxVarsPath())
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating sandbox vars directory: %w", err)
	}

	vars := map[string]string{
		"Zombies":             "1",
		"Distribution":        "1",
		"DayLength":           "1",
		"StartYear":           "1",
		"StartMonth":          "7",
		"StartDay":            "9",
		"StartTime":           "2",
		"WaterShutModifier":   "14",
		"ElecShutModifier":    "14",
		"WaterShut":           "2",
		"ElecShut":            "2",
		"FoodLootNew":         "2",
		"WeaponLootNew":       "2",
		"OtherLootNew":        "2",
		"Temperature":         "3",
		"Rain":                "3",
		"ErosionSpeed":        "3",
		"ErosionDays":         "0",
		"Farming":             "3",
		"CompostTime":         "1",
		"StatsDecrease":       "3",
		"NatureAbundance":     "3",
		"Alarm":               "2",
		"LockedHouses":        "3",
		"GeneratorSpawning":   "2",
		"SurvivorHouseChance": "3",
		"VehicleStoryChance":  "3",
		"ZoneStoryChance":     "3",
		"AnnotatedMapChance":  "2",
		"TimeSinceApo":        "1",
		"NightDarkness":       "3",
		"Helicopter":          "2",
		"MetaEvent":           "2",
		"SleepingEvent":       "2",
		"ZombieConfig": `{
            PopulationMultiplier = 0.65,
            PopulationStartMultiplier = 1.0,
            PopulationPeakMultiplier = 1.5,
            PopulationPeakDay = 28,
            RespawnHours = 0.0,
            RespawnUnseenHours = 0.0,
            RespawnMultiplier = 0.0,
            RedistributeHours = 12.0,
            FollowSoundDistance = 100,
            RallyGroupSize = 20,
            RallyGroupSizeVariance = 50,
            RallyTravelDistance = 20,
            RallyGroupSeparation = 15,
            RallyGroupRadius = 3,
            ZombiesCountBeforeDelete = 300,
        }`,
		"ZombieLore": `{
            Speed = 2,
            SprinterPercentage = 0,
            Strength = 2,
            Toughness = 2,
            Transmission = 1,
            Mortality = 5,
            Reanimate = 3,
            Cognition = 2,
            DoorOpeningPercentage = 0,
            CrawlUnderVehicle = 5,
            Memory = 2,
            Sight = 2,
            Hearing = 2,
            SpottedLogic = true,
            ThumpNoChasing = false,
            ThumpOnConstruction = true,
            ActiveOnly = 1,
            TriggerHouseAlarm = false,
            ZombiesDragDown = false,
            ZombiesCrawlersDragDown = false,
            ZombiesFenceLunge = true,
            ZombiesArmorFactor = 2.0,
            ZombiesMaxDefense = 85,
            ChanceOfAttachedWeapon = 6,
            ZombiesFallDamage = 1.0,
            DisableFakeDead = 1,
            PlayerSpawnZombieRemoval = 1,
        }`,
	}

	// SANDBOX_* env overrides may use Build 41 sandbox names, which b42
	// silently drops. Map the known renames to their b42 equivalents so
	// overrides keep working.
	legacyAliases := map[string]string{
		"FoodLoot":       "FoodLootNew",
		"WeaponLoot":     "WeaponLootNew",
		"OtherLoot":      "OtherLootNew",
		"SurvivorHouses": "SurvivorHouseChance",
		"MonthsSinceApo": "TimeSinceApo",
		"DarknessNight":  "NightDarkness",
	}

	for k, v := range c.SandboxVars {
		if alias, ok := legacyAliases[k]; ok {
			fmt.Printf("WARNING: SANDBOX_%s was renamed in b42, applying it to %s\n", k, alias)
			vars[alias] = v
			continue
		}
		vars[k] = v
	}

	var sb strings.Builder
	sb.WriteString("-- Generated by project-zomboid-server-docker\n")
	sb.WriteString("SandboxVars = {\n")

	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for i, k := range keys {
		sep := ","
		if i == len(keys)-1 {
			sep = ""
		}
		v := vars[k]
		sb.WriteString(fmt.Sprintf("    %s = %s%s\n", k, v, sep))
	}

	sb.WriteString("}\n")

	return os.WriteFile(c.SandboxVarsPath(), []byte(sb.String()), 0644)
}
